# Generated by Django 6.0.6 on 2026-06-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('progress', 'In Progress'), ('converted', 'Converted')], default='new', max_length=20),
        ),
    ]
